# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Node.js CI + deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    # - run: npm run test:unit
    - name: Install github-pages package
      run: npm install -g github-pages
    - name: Build and deploy to Github Pages
      run: |
        npm run build
        gh-pages -d dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # deploy:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [14.x, 16.x, 18.x]
  #   steps:
  #     - name: Install github-pages package
  #       run: npm install -g github-pages
  #     - name: Build and deploy to Github Pages
  #       run: |
  #         npm run build
  #         master -d dist
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}