name: Node.js CI + deployment

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ "./github/workflows/*" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skips all between the run in-progress and latest queued.
# does NOT cancel in-progress runs, allows them to complete
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test-build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: "npm"
    - run: npm ci
    - run: npm run build
    # - run: npm run test:unit
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload dist folder
        path: "dist"
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2